services:
  sports:
    image: ghcr.io/hackashaq666/zap2xml:latest
    restart: always
    volumes:
        - /xmltvdata:/data
    environment:
        - USERNAME=myemail@email.com
        - PASSWORD=**password**
        - OPT_ARGS=-I -D
        - XMLTV_FILENAME=sports.xml
